export const FETCH_COLLEGE_DATA = 'FETCH_COLLEGE_DATA';
export const FETCH_COLLEGE_DATA_SUCCESS = 'FETCH_COLLEGE_DATA_SUCCESS';
export const FETCH_COLLEGE_DATA_FAILURE = 'FETCH_COLLEGE_DATA_FAILURE';
export const SET_LOADER = 'SET_LOADER';

export const FETCH_SELECTED_COLLEGE = 'FETCH_SELECTED_COLLEGE';
export const FETCH_SELECTED_COLLEGE_SUCCESS = 'FETCH_SELECTED_COLLEGE_SUCCESS';
export const FETCH_SELECTED_COLLEGE_FAILURE = 'FETCH_SELECTED_COLLEGE_FAILURE';